#!/bin/sh
set -e

GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
WORKSPACE_ROOT="${CI_WORKSPACE:-$REPOSITORY_ROOT}"
OUTPUT_FILE="$WORKSPACE_ROOT/metar Watch App/GitCommit.swift"

cat > "$OUTPUT_FILE" << EOF
//
//  GitCommit.swift
//  Generated by ci_post_clone.sh
//

import Foundation

struct GitCommit {
    static let hash: String = "$GIT_COMMIT"
}
EOF

echo "Generated GitCommit.swift with commit hash: $GIT_COMMIT"
